spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - uri: lb://promise-platform-auth
          predicates:
            - Path=/api/v1/session/**
        - uri: lb://promise-platform-task
          predicates:
            - Path=/api/v1/tasks/**
        - uri: lb://promise-apps-server
          predicates:
            - Path=/api/v1/servers/**
    