spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: platform-auth-route
          uri: lb://promise-platform-auth
          predicates:
            - Path=/api/v1/session/**,/api/v1/users/**
        - id: platform-task-route
          uri: lb://promise-platform-task
          predicates:
            - Path=/api/v1/tasks/**
        - id: apps-server-route
          uri: lb://promise-apps-server
          predicates:
            - Path=/api/v1/servers/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG    