version: "3.5"

services:
  promise-platform-registry:
    network_mode: host
    environment:
      - CONFIG_SERVICE_URL
      - EUREKA_SERVICE_URL
  promise-platform-gateway:
    network_mode: host
    environment:
      - CONFIG_SERVICE_URL
      - EUREKA_SERVICE_URL
  promise-platform-task:
    network_mode: host
    environment:
      - CONFIG_SERVICE_URL
      - EUREKA_SERVICE_URL
      - MONGODB_HOST
      - MONGODB_PORT
      