version: "3.5"

services:
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: CONFIG_SERVICE_PASSWORD
    image: promise-platform-config:1.0.0
    ports:
      - 8888:8888
    network_mode: host    
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  registry:
    image: promise-platform-registry:1.0.0
    ports:
      - 8761:8761
    network_mode: host
    restart: always
