version: "3.5"

services:
  promise-platform-config:
    image: promise-platform-config:1.0.0
    ports:
      - 8888:8888
    network_mode: host    
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  promise-platform-registry:
    image: promise-platform-registry:1.0.0
    ports:
      - 8761:8761
    network_mode: host
    restart: always
  promise-platform-task:
    image: promise-platform-task:1.0.0
    ports:
      - 9001:9001
    network_mode: host
    restart: always
