spring:
  profiles:
    include: db
  application:
    name: promise-apps-server
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true     
    serialization:
      FAIL_ON_EMPTY_BEANS: false