logging:
  level:
    root: INFO
    org.springframework.security: INFO

spring:
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: ${KAFKA_BROKERS:kafka:9092}
  zipkin:
    baseUrl: ${ZIPKIN_SERVICE_URL:http://localhost:9411/}
    sender:
      type: web

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info
