spring:
  profiles:
    include: db
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
  data:
    mongodb:
      host: 100.101.64.180
      port: 27017
      database: task
server:
  port: 0