server:
  port: 8761
  
eureka:
  instance:
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: true  
  client:
    registerWithEureka: false
    fetchRegistry: false    