spring:
  profiles:
    active: db
  devtools:
    restart:
      log-condition-evaluation-delta: false
  application:
    name: promise-study-multi-tenant
log4j:
  category:
    org.springframework.data.mongodb: DEBUG    